### ISSUE TITLE
Invalid behaviour when using with livereload

### ISSUE THREAD

**Issue by mrmuh** [robrich/gulp-if#25]
i have noticed a problem when using gulp-if in combination with livereload. my goal is to trigger livereload only if the condition is true, but it seems that the "true branch" is always triggered. this behaviour only occurs with livereload ... 
```
.pipe(gulpif(false, livereload()));
```
version 1.1.0

**Comment by robrich** [comment]
I've been unable to reproduce this.  Can you help me pinpoint the fail?

**Comment by elgervb** [comment]
Hi @mrmuh,

looks like it's normal for the call `.pipe(gulpif(false, livereload()));` to execute the live-reload functionality. I had exactly the same problem at my repository https://github.com/elgervb/skeletonSPA.

Let me explain the situation:

The executionpath for this call is:

1. livereload
2. gulpif
3. pipe

Gulp-if expects a function as a second parameter, you're doing the function call right here in your gulpfile and by mistake pass the result of this function call.

Please change your original call `.pipe(gulpif(false, livereload()));` to:

`.pipe(gulpif(false, livereload));`

or

`.pipe(gulpif(false, function() { return livereload();} ));`


That will fix your problems... and this call can be closed.
