### ISSUE TITLE
Support multiple streams

### ISSUE THREAD

**Issue by gevgeny** [robrich/gulp-if#38]
It would be great if gulp-resources can pipe multiple streams passed as an array in second and third parameters.

```js
return gulp.src('/assets')
        .pipe(gif('**/*.js', [concat('js/min.js'), uglify()]))
        .pipe(gulp.dest('/dist/js'));
```

**Comment by KenPowers** [comment]
Might I suggest documenting this in `README.md`? I was about to fork and add multiple pipe support and then I saw that there were some issues open so I went ahead and looked at them.

**Comment by Marcel-Robitaille** [comment]
@popomore Worked for me, thanks! :D

**Comment by robrich** [comment]
I think using `merge-stream` is a safer alternative.
