### ISSUE TITLE
Gulp-If removes files from stream

### ISSUE THREAD

**Issue by chbloemer** [robrich/gulp-if#43]
Hello,
I have a strange problem with this code:
```javascript
gulp.task("copyScriptsBuggy", function () {
        return gulp.src("./source/scripts/**/*.{js,coffee}",{base:"./source/scripts"})
        .pipe(gulpif(/[.]coffee$/, coffee(), gutil.noop()))
        .pipe(gulp.dest("./build/scripts"));
});
```
I process about 200 files and about 10 files are missing in the destination folder. And they are not coffeescript files.
You can switch "coffee()" with "gutil.noop()" and there are still files missing, so its not a problem of coffeescript processing. As soon as "gulp-if" is used in the pipe, some files are not transfered to the destination folder.

My workaround was to use the "event-stream" modul to build two separate streams - one for coffee and one for javascript - and merge them. Now I have all files in my destination folder.
I think this is a little bit more complicated and I would prefer "gulp-if", if it would be working as expected.
```javascript
var es = require('event-stream'),
gulp.task("copyScriptsWorking", function () {
    return es.merge(
                gulp.src("./source/scripts/**/*.js",{base:"./source/scripts"}),
                gulp.src("./source/scripts/**/*.coffee",{base:"./source/scripts"}).pipe(coffee())
            )
            .pipe(gulp.dest("./build/scripts"));
});
```
I hope somebody can help with this.

Best regards
Christoph

Versions:
Gulp 3.8.9
Gulp-If 1.2.5
Gulp-Util 3.0.1
Node 0.10.33
NPM 2.1.6

**Comment by adrianhara** [comment]
Same problem here, about 30 files left out. Any fix in sight?

**Comment by davidgorges** [comment]
+1 
It was very hard to find this bug in an existing project.

**Comment by maskedcoder** [comment]
I have same problem.

My project is based on the [Google Web Starter Kit](https://github.com/google/web-starter-kit), using
- node 0.12.0
- gulp 3.8.11
- gulp-if 1.2.5
- gulp-uglify 1.1.0
- gulp-useref 1.1.1
- gulp-load-plugins 0.6.0

The code I'm using is something like this:
```javascript
gulp.task('html', function () {
  var assets = $.useref.assets({searchPath: '{.tmp,app}'});

  return gulp.src('app/**/*.html')
    .pipe(assets)
    // Concatenate And Minify JavaScript
    .pipe($.if('*.js', $.uglify({preserveComments: 'some'})))
    // Remove Any Unused CSS
    // Note: If not using the Style Guide, you can delete it from
    // the next line to only include styles your project uses.
    .pipe($.if('*.css', $.uncss({
      html: [
        'app/index.html'
      ]
    })))
    // Concatenate And Minify Styles
    // In case you are still using useref build blocks
    .pipe($.if('*.css', $.csso()))
    .pipe(assets.restore())
    .pipe($.useref())
    // ...
    // Output Files
    .pipe(gulp.dest('dist'))
    .pipe($.size({title: 'html'}));
});
```
(`$` contains all the plugins.) When I run this, at least one file gets skipped.

If I run the task repeatedly, it will always skip the same file (or files). However, when I add a new file to my scripts folder, the plugin changes which files get skipped.

**Comment by jzorn** [comment]
Is there an update on the status of this?

**Comment by nevech** [comment]
I have some problem.

```js
gulp.task('scripts', function () {
  return gulp.src('app/scripts/**/*.{js,coffee}')
    .pipe($.plumber())
    .pipe($.watch('app/scripts/**/*.{js,coffee}'))
    .pipe($.if('*.coffee', $.coffee()))
    .pipe($.ngAnnotate())
    .pipe(gulp.dest(config.destDir + '/scripts'));
});
```
($ - gulp-load-plugins)
It's work, but if an error occurs in coffee or other tasks and after fix the error `gulp-if` blocks stream.

**Comment by robrich** [comment]
Do you have an example gulpfile gist or pastebin?

**Comment by nevech** [comment]
Yes, see: https://gist.github.com/nevech/8ff0b5630169128be078

**Comment by jessepollak** [comment]
+1 I'm having this issues as well. It only affects one file and it happens after running `gulp-cssmin`. The file is very small if that helps at all.

**Comment by alexgorbatchev** [comment]
`gulp-if` has 285k monthly installs and this issues has been open for 10 months now. I think it's worth mentioning this issue in README and discouraging people from using this in production env until this is resolved.

**Comment by jessepollak** [comment]
@alexgorbatchev I used `gulp-if-else` and it fixed the issue.

**Comment by robrich** [comment]
@everyone I still can't reproduce this.  Can someone give me a PR with failing tests or a github repo that fails in this way?

**Comment by robrich** [comment]
I think I may have caught this in the act, and moving from `duplexer2` to `duplexify` seems to have solved it.  Please reply if you're still having this issue after upgrading to `gulp-if@2.0.0`.

**Comment by chbloemer** [comment]
I just tried my old branch with version 1.2.5 where this bug happened, but I had to do a new "npm install".
So my dependencies are maybe different than last year.
I couldn't reproduce the bug anymore. :-/

**Comment by robrich** [comment]
Seems like it's now resolved.  If anyone has a similar concern, start a new issue.
