### ISSUE TITLE
Error: Cannot find module 'merge-stream'

### ISSUE THREAD

**Issue by M165437** [robrich/gulp-if#45]
I'm getting an `Error: Cannot find module 'merge-stream'` on gulp-if version 1.2.5 just on requiring the module. I'm not even using it (yet). Downgrading to 1.2.4 helped. A general bug or am I doing something wrong?

```
var gulp		= require('gulp'),
	gulpif		= require('gulp-if');
```

**Comment by robrich** [comment]
I can't reproduce this.  Try `npm cache clean` and reinstall.

**Comment by M165437** [comment]
It did help. Thanks!
