### ISSUE TITLE
Is it possible to chain pipes?

### ISSUE THREAD

**Issue by cappslock** [robrich/gulp-if#46]
While using [css-sprite](https://github.com/aslansky/css-sprite) in a gulp step, I noticed that I can't do this:

```
.pipe(
  gulpif('*.png',
    imagemin().pipe(gulp.dest('./assets/img/sprites')),
    gulp.dest('./scss/sprites')));
```

The imagemin() step in the pipe seems to be skipped entirely, although the gulp.dest() call still works. Why is this? Am I using this improperly?

I've noticed that I can achieve the desired behavior with:
```
.pipe(gulpif('*.png', imagemin()))
.pipe(gulpif('*.png', gulp.dest('./assets/img/sprites'), gulp.dest('./scss/sprites')));
```
... but I'd still like to understand what's happening in the first case.

**Comment by robrich** [comment]
In the first example, what you're returning as an input pipe and the output pipe to gulp-if is the last element in the chain -- in this case the gulp.dest().  Ideally you'd return the first pipe as the input pipe and the last as the output pipe.  Look at lazipipe to be able to do this, then return the results of lazypipe to gulpif.

**Comment by cappslock** [comment]
Got it. Thanks for the clarification.
