### ISSUE TITLE
Stream still being called

### ISSUE THREAD

**Issue by callumacrae** [robrich/gulp-if#47]
I have the following code:

```js
function handleOptimize() {
    function losslessTest(file) {
      return options.lossless;
    }

    var lossyStream = plugins.imagemin({ use: [jpegoptim({ max: 80 })] });
    var losslessStream = plugins.imagemin({ progressive: true });

    return plugins.if(losslessTest, losslessStream, lossyStream);
  }
```

It's simplified: `losslessTest` does do something useful in real life.

When piping four images through this, I get the following output:

```
[16:53:15] gulp-imagemin: Minified 0 images
[16:53:15] gulp-imagemin: Minified 0 images
[16:53:15] gulp-imagemin: Minified 0 images
[16:53:15] gulp-imagemin: Minified 0 images
[16:53:15] gulp-imagemin: Minified 1 image (saved 273 B - 6.4%)
[16:53:15] gulp-imagemin: Minified 1 image (saved 319 B - 4.9%)
[16:53:15] gulp-imagemin: Minified 1 image (saved 398 B - 3.2%)
[16:53:16] gulp-imagemin: Minified 1 image (saved 1.55 kB - 3.4%)
```

Is that supposed to happen? Will it cause other problems in my code?

**Comment by robrich** [comment]
That isn't.  Do you have a test project or paste-bin that shows this symptom?

**Comment by callumacrae** [comment]
https://github.com/callumacrae/gulp-if-bug

**Comment by robrich** [comment]
@callumacrae: Thanks for the example repo. I see it says output true: 1
file, false: 0 files. What results were you expecting?

**Comment by callumacrae** [comment]
I expected this, but I'm not sure it's any better:

```
true: 1 files
```

Six months later, now I know more about streams, I would expect the output we have now. Not sure why it is better, though.

**Comment by robrich** [comment]
Oh, I see. You don't like that the false stream is included in the pipeline
at all when your results don't include any files that run through it. Yeah,
not sure we can do anything about that since we don't know whether it will
be used when we set up the pipeline at the beginning.

**Comment by callumacrae** [comment]
Fair enough. Also, not sure if there are any advantages to it, either. I'll close this issue
