### ISSUE TITLE
Can't get 'if' to match globstar path for JS/CSS

### ISSUE THREAD

**Issue by alias1** [robrich/gulp-if#49]
It seems no matter what way I try, I can't get gulp-if to seperate out file paths

Cut down file:

```js
var $ = require('gulp-load-plugins')();

gulp.src(paths.src + '/foo/*')
    .pipe($.debug({title: 'Assets:', minimal: false}))
    .pipe($.if('**/*.js', $.debug({title: 'JS:', minimal: false})))
    .pipe($.if('**/*.css', $.debug({title: 'CSS:', minimal: false})));
```

The Assets debug line is definitely showing 4 files (2 css, 2 js)

I also tried using match explicitly, but had the same issue:
```js
  var isJs = function (file) {
    $.match(file, '**/*.js');
  };

  var isCss = function (file) {
    $.match(file, '**/*.css');
  };

gulp.src(paths.src + '/foo/*')
    .pipe($.debug({title: 'Assets:', minimal: false}))
    .pipe($.if(isJs, $.debug({title: 'JS:', minimal: false})))
    .pipe($.if(isCss, $.debug({title: 'CSS:', minimal: false})))
```

Any ideas? I'm not sure if i'm doing something wrong or it's something within gulp-if

Thanks! :3

**Comment by robrich** [comment]
Try messing with globs: './**/*.js' or '*.js' Globs are weird, especially
on windows.

**Comment by alias1** [comment]
Definitely tried just *.js, the ./ probably wouldn't work since it's already prefixed with the full path anyway, but I can try it.




The same glob matching works in filter, just not if, which was making me think it was an issue here.




This is on osx.



—

**Comment by alias1** [comment]
Hrmm.. I stand corrected, I musn't have tried `*.js`..

```
    .pipe($.if('*.js', $.debug({title: '*.js', minimal: false})))
    .pipe($.if('**/*.js', $.debug({title: '**/*.js', minimal: false})))
    .pipe($.if('./*.js', $.debug({title: './*.js', minimal: false})))
    .pipe($.if('./**/*.js', $.debug({title: './**/g*.js', minimal: false})))
    .pipe($.if(isJs, $.debug({title: 'isJS:', minimal: false})))
```

Output
```
[08:43:45] *.js 
cwd:   ~/dev/foo
base:  ~/dev/foo/.tmp/serve/
path:  ~/dev/foo/.tmp/serve/scripts/vendor-eac523fd.js

[08:43:46] *.js 
cwd:   ~/dev/foo
base:  ~/dev/foo/.tmp/serve/
path:  ~/dev/foo/.tmp/serve/scripts/app-3b9319d8.js

[08:43:46] *.js 2 items
[08:43:46] **/*.js 0 items
[08:43:46] ./*.js 0 items
[08:43:46] ./**/*.js 0 items
[08:43:46] isJS: 0 items
```

It's strange that [gulp-filter](https://www.npmjs.com/package/gulp-filter) seems to work fine with the `**/*.js` pattern, yet gulp-if doesn't.

Differences:

* gulp-if uses [gulp-match](https://www.npmjs.com/package/gulp-match) which uses [minimatch](https://www.npmjs.com/package/minimatch), which definitely supports `**` syntax (unless `noglobstar` is set)
* [gulp-filter](https://www.npmjs.com/package/gulp-filter) uses [gulp-multimatch](https://www.npmjs.com/package/multimatch) which just seems to add array support to [minimatch](https://www.npmjs.com/package/minimatch)
