### ISSUE TITLE
any suggestion for .pipe( gulpif(condition, runSequence(gulpfilter, gulp-renamem, ..) , elseTask )  )?

### ISSUE THREAD

**Issue by miukki** [robrich/gulp-if#51]
i want for .pipe( gulpif(condition, runSequence(gulpfilter, gulp-renamem, ..) , elseTask )  )?

**Comment by popomore** [comment]
use [multipipe](https://www.npmjs.com/package/multipipe)

**Comment by robrichnsons** [comment]
Look at the docs on https://github.com/robrich/gulp-if and scroll down to "ternary".  It's already built-in.

**Comment by robrich** [comment]
Look at the docs on https://github.com/robrich/gulp-if and scroll down to "ternary".  It's already built-in.
