### ISSUE TITLE
Any changelog?

### ISSUE THREAD

**Issue by amio** [robrich/gulp-if#55]
Recently gulp-if have updated to 2.0, I think maybe there is some breaking change, but couldn't find any changelog to see if I can upgrade my dependency safely.

Will there be a changelog or tag/release(helpfull too)?

**Comment by robrich** [comment]
Great idea.  I mostly bumped the major version because some dependencies bumped major versions, but the upgrade should be safe.  The only major functional change is it now matches on `file.relative` rather that the previous behavior of matching on `file.path`.

**Comment by Nirazul** [comment]
+1

**Comment by chrisjlee** [comment]
+1 changelog please. Also, why aren't there git tagged versions?

**Comment by notiv-nt** [comment]
@robrich add a changelog, at least "3.0.0: No breaking changes"

**Comment by robrich** [comment]
The only breaking changes were in dependencies. 3.0.0 now requires a
runtime that supports ES6.
