### ISSUE TITLE
Can it support "if is last one"?

### ISSUE THREAD

**Issue by Awakening-j** [robrich/gulp-if#60]
something like
```
gulpif('is last file', dosomething())

**Comment by robrich** [comment]
Kinda.  This is a gulp paradigm moreso than a gulp-if paradigm.  Listen for `on('end',` or `on('finish',` or both (readable stream vs. writable stream) and take action.  It isn't so much "the last file through the stream" as it is "after everything has gone through the stream -- including the last one."
