### ISSUE TITLE
Does not work with ES2015 arrow functions

### ISSUE THREAD

**Issue by thewebdreamer** [robrich/gulp-if#63]
I'm been trying to use gulp-if with arrow functions. These don't work for me as I get an error about dest.on.

Is it because arrow functions have 'this' lexically binded to them?

**Comment by robrich** [comment]
Yes, rebinding this with arrow functions does weird things to streams. You
may be able to shim it in with bind, but are you saving characters? May be
better to just use function.

**Comment by thewebdreamer** [comment]
I've been using arrow functions with gulp itself for my tasks and I haven't had any trouble with it. I'll use functions for now with gulp-if.

**Comment by robrich** [comment]
Quite interesting.  Do you have a pastebin or github repo that demonstrates arrow functions working in tasks but not in gulp-if?
