### ISSUE TITLE
Gulp if doesn't stop gulp.dest from being run

### ISSUE THREAD

**Issue by jahumes** [robrich/gulp-if#64]
I am trying to write a function that returns a lazypipe that only sends to gulp.dest if a destination was passed.

```
function filterScripts(destination, templateName) {
    var jsFilter = $.filter('**/*.js');
    var hasDestination = (typeof destination !== 'undefined');

    return lazypipe()
        .pipe(function() { return jsFilter })
        .pipe(sourceMaps(scripts(templateName),templateName))
        .pipe(function() {
            return $.if(hasDestination, gulp.dest(destination), console.log(hasDestination));
        })
        .pipe(jsFilter.restore);
}
```

When I do this, I get an `Error: Invalid output folder` error. I know that the hasDestination variable is false at this stage, but the gulp.dest still fires.

**Comment by robrich** [comment]
`gulp.dest(...)` is a stream, but `console.log(...)` isn't.  I suspect that's where things fell off.  Try this:

	function log(file, enc, cb) {
	    console.log(hasDestination);
	    cb.push(null, file);
	}

	// ...

	$.if(hasDestination, gulp.dest(destination), log);

or just try this:

`$.if(hasDestination, gulp.dest(destination));`

**Comment by vikas0380** [comment]
@jahumes You can use `process.stdout.write(hasDestination)` instead of `console.log(hasDestination)`
