### ISSUE TITLE
resume after gulp if condition false

### ISSUE THREAD

**Issue by seeliang** [robrich/gulp-if#65]
Hi @robrich 

thank you for the plugins gulp-if and gulp-ignore .

i not sure which plugin should i use in my case 

pipe (if true => do this => resume to new condition, if false => resume new condition)
pipe (new condition => if true ... )

could you help?

**Comment by robrich** [comment]
`...pipe(gulpIf(someCondition, doThis()).pipe(...`

If your condition depends on the filename or an external condition, gulp-if seems the better choice.  gulp-if will only run your pipe if the condition is true, and in either case will continue down stream.

**Comment by seeliang** [comment]
cool, thanks @robrich
