### ISSUE TITLE
Does not support node@6.2.0

### ISSUE THREAD

**Issue by littledu** [robrich/gulp-if#68]
Does not support node@6.2.0

**Comment by robrich** [comment]
Can you be more specific? What are repro steps? Can you PR a failing test?

**Comment by AlexandreAWE** [comment]
+1 gulpif does not filter files when we use it like this : 
`.pipe($.if('*.js', $.uglify()))`

Try to uglify also html files

**Comment by robrich** [comment]
Do you have an example repo or pastebin or can you PR a failing test?

**Comment by robrich** [comment]
Sounds like the glob may be awry.  Try this: `.pipe($.if('**/*.js', $.uglify()))`

**Comment by robrich** [comment]
... still can't repro "doesn't work in node@6.2.0".  See https://travis-ci.org/robrich/gulp-if/jobs/140276224 where it succeeds.

**Comment by AlexandreAWE** [comment]
Thx @robrich it works ! :)

**Comment by littledu** [comment]
Thx @robrich 。
