### ISSUE TITLE
RegularExpression conditional stopped working after updating to node 6.2.2

### ISSUE THREAD

**Issue by dobesv** [robrich/gulp-if#69]
We used to use the condition `/[.]coffee$/` to only process CoffeeScript files using the coffee plugin.  After updating `node`, it started reporting weird syntax errors in the JavaScript files, which I eventually figured out was because it was calling `coffee` on JavaScript files.  I changed the condition to a function instead, which worked as expected.

I have created a sample project that reproduces the issue for me:

https://gist.github.com/dobesv/0175640a973bd5557ad3fcf982eb49f1

**Comment by davidgorges** [comment]
Same with node 6.3

**Comment by dogancelik** [comment]
Yeah I noticed this too

**Comment by joserobleda** [comment]
I've just reinstalled the latest version (`"gulp-if": "^2.0.1"`) and it works fine.
