### ISSUE TITLE
Log error in sass

### ISSUE THREAD

**Issue by soulcreate** [robrich/gulp-if#72]
How right send error in sass?
I try:
```
gulp.src './app/styles/*.{scss,less,styl}'
	.pipe $.if('**/*.scss', $.sass({outputStyle: 'compressed',precision: 10}).on('error', $.sass.logError))
	.pipe $.if('**/*.less', $.less())
	.pipe $.if('**/*.styl', $.stylus())
	.pipe cssMin()
	.pipe gulp.dest './app/styles/css'
```
But if sass have error my pipe broken...

**Comment by robrich** [comment]
I'm failing to see the bug.  Do you get the same behavior when you don't use gulp-if?

**Comment by soulcreate** [comment]
some problem. Resolved. You must don't use gulp-if. Use separate gulp tasks.  [link](https://github.com/robrich/gulp-if/issues/57)
